spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tester
    username: igor
    password: ni30uywiw
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
#      data-locations: classpath:demo_data.sql

security:
  jwt:
    secret: YXNkYXNzZEFTQURTSEZHS1NESkhGNTQ0NTZGRExkZnNkZmxha3NkYXNkbHNnZGRm
    access: 3600000
    refresh: 2592000000

